V1.0 development (just a draft PR to view the diff)
cafkafk/eza pull request #787
Opened 2024-01-17 23:21 UTC by PThorpe92

this is so everyone can fork this branch, and make their own edits, add whatever features, etc. so instead of a massive PR that is impossible to review, we can each add things incrementally

2024-01-21 21:02 UTC, PThorpe92 commented
I see the git history is diverged enough where it might have to be rebased off main to one commit :/

2024-01-21 22:55 UTC, MartinFillon commented
Gonna merge and update it

2024-01-21 23:16 UTC, MartinFillon approved these changes, later dismissed

2024-02-02 20:31 UTC, MartinFillon commented
Okay so how are we doing on that v1.0 release ?

2024-02-03 12:04 UTC, MartinFillon submitted a review, later dismissed

2024-02-03 13:10 UTC, PThorpe92 commented
I'm all for it. Yeah this is really more about clap and anything that would come along with it that would have breaking changes than it would be actually 1.0

2024-02-03 15:08 UTC, MartinFillon commented
Well guess this can be made ready for review ?

2024-02-14 19:36 UTC, MartinFillon commented
Hey @tertsdiepraam you created a breaking change on time-style argument, could you have a look at it
For an exemple please see  the test file named `long_time_style_custom_non_recent_and_recent_nix.toml` and tell me if its intended.

2024-02-14 21:53 UTC, tertsdiepraam commented
@MartinFillon I don't think it's due to my changes. With `git bisect` I've narrowed it down to this commit where the time-style does not accept `"+NON_RECENT\n    RECENT"`: https://github.com/eza-community/eza/commit/47b9e454cf26a730c321cc4fd7bce0439f02c80a

2024-02-14 22:00 UTC, MartinFillon commented
Well my bad sorry 😞 I should have bisect more in depth

Gonna fix it

2024-02-16 23:22 UTC, MartinFillon commented
This is ready @cafkafk

2024-02-17 09:53 UTC, cafkafk commented
> This is ready @cafkafk

Okay let's get going on review then!

2024-02-17 09:54 UTC, cafkafk requested changes
First order of business is to resolve clippy lints so CI pass it seems

2024-02-17 11:28 UTC, MartinFillon commented
I can't understand nix flake check outputs. It seems to always fail

2024-02-17 12:48 UTC, tertsdiepraam commented
Seems to be a formatting issue. I think `nix fmt` can fix it, but `cargo fmt` doesn't seem to fix it, which seems strange, because `nix fmt` should essentially be running `cargo fmt` under the hood. Maybe the `rust-toolchain.toml` file might be ignored by `nix` and it will therefore run a newer version of rustfmt?

2024-02-17 14:16 UTC, MartinFillon commented
well thats strange Should I fix it ?

2024-03-04 14:41 UTC, MartinFillon commented
I fixed the pr and updated it

2024-03-12 21:36 UTC, MartinFillon commented
@cafkafk the PR is ready

2024-04-07 22:10 UTC, MartinFillon commented
Hey just a heads up to say that the pr is up to date

2024-05-23 14:52 UTC, MartinFillon commented
Hey, just a heads up, how do we think this should go ?

2024-07-04 20:19 UTC, MartinFillon commented
Hey @PThorpe92 could you check if i did the migration correctly of your pr in this one.

If everything is okay it is ready for review @cafkafk

2024-07-04 20:21 UTC, MartinFillon approved these changes, later dismissed

2024-07-20 17:02 UTC, cafkafk commented
This is such a large change it's very hard for me to find actual time to review it all. If other people want to add their reviews as well, they should feel free to do so, it could be good to have more eyeballs on this

2024-09-12 14:02 UTC, MartinFillon commented
Up @cafkafk

2025-02-12 06:22 UTC, dofuuz commented
Any updates for this? 👀
I'm waiting for #337 to be fixed.

2026-04-10 14:41 UTC, closed without merging